service: qmatic-mobile-client-test

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2

plugins:
  - serverless-finch

custom:
  client:
    bucketName: s3-qmatic-mobile-client
    distributionFolder: dist
